### ISSUE TITLE
[BUG] Unbalanced forces for continuous member connections in version 21.1.3 ?

### ISSUE THREAD

**Issue by ozbuild** [idea-statica/ideastatica-public#105]
The member force results for a continuous member in a connection seem to be calculated differently between version 21.1 and 20.1

When we use 20.1 we get balanced forces, now when using 21.1 we get a different set of forces for the continuous member and hence unbalanced forces. The other connected member forces are correct.

We cannot determine whether this is a bug or if you are now recalculating member forces for continuous members in a different way with the newer version.

This is the member forces that are created in version 21.1.3.1398, unbalanced

![image](https://user-images.githubusercontent.com/79124821/150051525-57b6763e-1114-49ac-8b07-9c73d7cf5350.png)

This is the member forces that are created in version 20.1.5544.1, all forces balanced

![image](https://user-images.githubusercontent.com/79124821/150051886-f41a6318-3b1f-46c4-99bf-d446de322e48.png)

We use the ConnHiddenClientFactory to specify the install version of the program

I have attached the xml and xmlr result file that we use and the two connection files that are created in each version.

Are you able to provide the new method of specifying the results for a continuous connection member if it has been changed from the older version. 

[IdeaCon and xml.zip](https://github.com/idea-statica/ideastatica-public/files/7893656/IdeaCon.and.xml.zip)

**Comment by vojtech-chalupa** [comment]
Hello, there was indeed a slight change in how the load effects and their values are set to a connection project from continuous members. The reason is that since version 21, we are dealing with models of the whole structure in the Checkbot app, and we need to ensure data consistency between both workflows (generating a single connection project & importing a whole structure to Checkbot and generating multiple connections based on that).

When specifying the results in the .xmlr file, you are basically describing internal force diagrams for all load components along a given beam. You are currently specifying internal force values in the relative positions 0 and 1. However, the connection point is in the middle of the continuous Member 79 in your case (relative position 0.5). To get to the values needed, we currently:

a) read it directly (if available), or
b) interpolate between the two closest defined values (relative positions 0 and 1 in your case)

Please refer to the image below, where I've outlined your geometry and internal force diagrams for the normal and shear force - explaining the values that you see after import in version 21.1.3 on Member 79.

![image](https://user-images.githubusercontent.com/73105487/150117752-f5dbee3d-c248-4574-8c46-1ef136c57063.png)

Now, there are two ways of dealing with this. Internally, we use both of them, depending on the API of the 3rd party software:

A) In order to read the "before" and "after" values in a connection point, we look for sections **1e-6** away from the connection point (relatively). So in your case, you can add those relative sections (0.499999 and 0.500001) and get equilibrium (example attached).

B) Define multiple Elements1D for continuous members and define the results for those Elements1D; rather than the whole Member. So in your case, you would define two Elements1D to construct the Member 79 (from point 85 to 99 and from point 99 to 86). When creating the connection, we'd then take the results directly from the endpoint of the first Element1D (rel. pos. 1), and the start point (rel. pos. 0) of the second Element1D. I can create that example too, if required

[XML.zip](https://github.com/idea-statica/ideastatica-public/files/7896956/XML.zip)

**Comment by ozbuild** [comment]
Thanks for your very prompt reply and clear explaination.

We have now implemented you’re a) method and it now works correctly and the issue is now resolved.

Regards

Mark Watson

**Comment by ozbuild** [comment]
Sorry, just reopening this issue. We are trying your Method B as this would be our preferred method, but have been unsuccessful in getting it to work. There seems to be some internal adjustment of forces that is happening that we cannot work out.
I have attached the xml files we have created based on your method but you will see that the forces are unbalanced and the 79and 83  end values are not what it is in the xmlr file, they seem to have been adjusted in some way?

![image](https://user-images.githubusercontent.com/79124821/150475502-2d8e04a3-aedf-4cf4-82a9-213c66a2491b.png)

![image](https://user-images.githubusercontent.com/79124821/150475832-c916fe8a-764d-4894-a6f1-6a0efb90b567.png)

![image](https://user-images.githubusercontent.com/79124821/150476255-0a479303-3452-4f43-8ecc-89407e8b29c8.png)


I have attached the xml and xmlr and connection file for your perusal.

If you could provide some guidance it would be appreciated.

[Portal_Frame method B.zip](https://github.com/idea-statica/ideastatica-public/files/7910853/Portal_Frame.method.B.zip)

**Comment by vojtech-chalupa** [comment]
No problem, the IOM seems to be correct at first glance. Will investigate and follow up.

**Comment by vojtech-chalupa** [comment]
I've simplified your results file to one load case just to make it easier to read, but more importantly, I've added one more section on every element. It seems that having the results defined in a single point was causing issues (since we are actually drawing a force diagram in the background, it is safer to use a minimum of two sections along each element). Should work for you now.

[Portal_Frame.method.B_edited.zip](https://github.com/idea-statica/ideastatica-public/files/7911693/Portal_Frame.method.B_edited.zip)
