### ISSUE TITLE
[BUG] ConnHiddenClientFactory - method CreateConProjFromIOM is failed

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#199]
Hi,
In the newest version of API (22.1.0.3519), method CreateConProjFromIOM does not create ideacon file.

```
var calcFactory = new ConnHiddenClientFactory(fileInfo.DirectoryName);
 using (var client = calcFactory.Create())
	{
        client.CreateConProjFromIOM(tempFiles.OpenModelTempFile, tempFiles.OpenModelResultTempFile, newIdeaFileName);
	}
```

[IdeaStatiCaConnHiddenCalculator.zip](https://github.com/idea-statica/ideastatica-public/files/9784206/IdeaStatiCaConnHiddenCalculator.zip)

**Comment by nathanlukeIDEA** [comment]
Hi rewiteq,

Sorry for the slow response on this one. I believe there was a small issue when reading in plate data by svg string in the latest release, however, this should now be fixed in the next patch due in the next couple of weeks. 

For your information, plate geometry can now be defined by Region2D (not the SVG string that is being provided). 

https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Geometry/Geometry2D/Region2D.cs

Hopefully, this makes it a lot easier now to define plate geometry. 

Cheers
Nathan
