### ISSUE TITLE
Parameter values are not set to model

### ISSUE THREAD

**Issue by JRiad** [idea-statica/ideastatica-public#373]
**Parameter values are not set to model**

I almost finished the Grasshopper script I’m working on, but ran into an issue at the end. The example I’m doing is quite simple. I want to change the load effect and bolt size for an existing connection. When I run my script, the load changes as it should, but it seems the “Connection Results” are from the model with the old bolt sizes.
When I open the new saved Idea Statica model, the parameter value has changed but I need to press “Set to model” for the changes to be applied. 
 
![2](https://github.com/idea-statica/ideastatica-public/assets/89396751/ae7226ce-a8cf-4d87-a146-f05198d507c9)
![1](https://github.com/idea-statica/ideastatica-public/assets/89396751/be2ca024-3d83-41fb-9d78-6bee4e4f0bc5)

**Comment by nathanlukeIDEA** [comment]
I have looked into this and there is a problem with parameters changing Material database items. 

For a work around, If you set up the Bolt Assembly parameters by changing the operation Bolt Assembly library reference to others you have pre-defined in your project (instead of directly changing the bolt assembly item, it should work okay: 

1.0 
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/d58d8f3d-f353-4245-a9e5-0f0f620c9c03)


 
2.0 Define the parameter to the Operation Bolt Assembly Types, instead of changing the Material database item directly.
 
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/4a3fce42-f1dd-46e3-997a-b6792cc56b37)

**Comment by nathanlukeIDEA** [comment]
Hi @JRiad, this particular issue is now fixed 23.1.2.
