### ISSUE TITLE
Connections" and "Member" commands

### ISSUE THREAD

**Issue by EdoardoNagliati** [idea-statica/ideastatica-public#420]
Good morning,

We are developers of Finite Element Method (FEM) software that integrates with Idea StatiCa via the Checkbot interface.

We have identified a bug that emerged with the release of version 23.1.2.1027, dated December 15, 2023. As evident in the attached documentation, the "Connections" and "Member" commands, essential for completing the import process into Checkbot, are no longer functional. This issue was not present in version 23.1.1.1138 and earlier releases.

Furthermore, we have observed that other FEM software, such as SAP 2000, also relies on these commands for import completion, suggesting a potentially widespread issue.

Could you provide any guidance on resolving this matter? Is it necessary to modify the link plugin to accommodate these changes?

We appreciate your attention to this matter and seize this opportunity to wish you a Happy New Year.

![vs 23 1 1 1138](https://github.com/idea-statica/ideastatica-public/assets/132692405/ab11fb0b-c0db-406c-9a5c-f3b5fb4cd238)
![vs 23 1 2 1027](https://github.com/idea-statica/ideastatica-public/assets/132692405/ec9d843f-e966-4a93-88b3-d82af46d027c)

**Comment by sonkaste1** [comment]
Hello @EdoardoNagliati ,

thank you for raising this issue here on GitHub.

The issue is caused by the cutoff of obsolete WCF communication technology in IDEA 23.1.2. release.
Unfortunately, WCF was still available on our GitHub repositories in various places and the cutoff was not communicated here as it was supposed to be, I am very sorry about that.

**In detail**:
Communication between BIM plugins and IdeaStatiCa Checkbot using  [BIMPluginHosting](https://github.com/idea-statica/ideastatica-public/blob/23.1.2.1027/src/IdeaStatiCa.Plugin/BIMPluginHosting.cs) is not supported anymore. 
It uses WCF which is used is deprecated technology now.
Communication with IDEA should migrate in BIM plugins to gRpc communication (see BIMPluginHostingGrpc )

examples of usage can be found here :

see [BimApiFeaLinkExample](https://github.com/idea-statica/ideastatica-public/blob/main/examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/TestPlugin.cs)
or [FEAppExample_1](https://github.com/idea-statica/ideastatica-public/blob/main/src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs)


                 public void Run(object param)
                 {
                          Logger.LogInformation($"Run param = '{param?.ToString()}'");
                          var factory = new PluginFactory(this);
                          Logger.LogDebug("Run - calling GrpcBimHostingFactory");
                          var bimHostingFactory = new GrpcBimHostingFactory();
                          var pluginHostingGrpc = bimHostingFactory.Create(factory, Logger);
                          FeaAppHosting = pluginHostingGrpc;
                          this.IdeaStatica = ((ApplicationBIM)FeaAppHosting.Service).IdeaStaticaApp;

                          FeaAppHosting.AppStatusChanged += new ISEventHandler(IdeaStaticAppStatusChanged);
                          var id = Process.GetCurrentProcess().Id.ToString();

                          ProjectDir = Path.Combine(WorkingDirectory, ProjectName);
                          if (!Directory.Exists(ProjectDir))
                          {
                                   Logger.LogDebug($"Run - creating new project dir '{ProjectDir}'");
                                   Directory.CreateDirectory(ProjectDir);
                          }
                          else
                          {
                                   Logger.LogDebug($"Run - using existing dir '{ProjectDir}'");
                          }
 


In case you need more help with migration to gRpc communication, let us know.

Best regards,

**Comment by nathanlukeIDEA** [comment]
https://developer.ideastatica.com/docs/bimapi/bim_api_breaking_changes.html
