### ISSUE TITLE
Visual Studio version

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#46]
Is it possible to use the IdeaRS.OpenModel.dll version 21.0.0.3277 with VisualStudio 2017 somehow, or we need to have VisualStudio 2019 to use it in a C++/CLI project?

**Comment by mpospisil** [comment]
IdeaRS.OpenModel is available as the nuget package

https://www.nuget.org/packages/IdeaStatiCa.OpenModel/

Our nuget package depends on .NET Framework 4.8. It means your project should be compatible with .NET Framework 4.8
If you need an older .NET Framework you can modify the target framework for  IdeaRS.OpenModel.csproj and create your own build.

In the future we want to port the code so that it is compatible with .NET Standard

**Comment by zsolt4un** [comment]
Thank you for the explanation!
