### ISSUE TITLE
Understanding internal forces in IdeaRS.OpenModel

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#47]
Our customers found a huge difference in the internal forces between two IDEA StatiCA versions the 20.0 and the 21.0. 
The Vy and Vz columns are replaced with each other, just like the My and Mz columns, and some values are also multiplied with -1.
You can find the figures here: 
![#CS-9902 CS14 - IDEA 20 0 92 57482](https://user-images.githubusercontent.com/87762551/126488277-f5860178-362a-42c8-97f0-7507966f5bae.png)
![#CS-9902 CS14 - IDEA 21 0 0 3277](https://user-images.githubusercontent.com/87762551/126488317-6d77f80c-eda4-4291-9fa4-f70ee2b6f03b.png)

Earlier we had a meeting where one of your colleagues mentioned, that we can use local coordinate systems to fix these kind of issues. Now I have implemented the local coordinate systems by creating CoordSystemByVector objects and gave them to the LocalCoordinateSystem parameter of the LineSegment3D objects.
(ConSteel has similar local system to IDEA StatiCA, which I’ve found here: https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.Result.ResultOfInternalForces.html and here https://idea-statica.github.io/iom/coord-system.html.)
I tried to check the effect of the local coordinate systems on the internal forces.
I have tried two cases: 
-	in the first case I set the local system X axis pointing from the start to the endpoint of the beams, 
-	in the second case I set the local system X axis pointing from the endpoint to the start point of the beams.
 
I have checked both cases with the IDEA Statica CON 21.0.0.3277 version, but it has no effect on the values in the loadcase table.
You can find the figures here:
![#CS-9902 CS14 - IDEA 21 0 0 3277 - Case1](https://user-images.githubusercontent.com/87762551/126488490-f2d85b14-f791-4484-8ad8-24b1408a7c11.PNG)
![#CS-9902 CS14 - IDEA 21 0 0 3277 - Case2](https://user-images.githubusercontent.com/87762551/126488555-a44015ba-8800-43cf-b42b-de00d6c0c8cf.PNG)

I attach here the IdeaRS.OpenModel generated xml and xmlR files of the examples.
I have also prepared a copy of these files with line breaks to make it easier to compare them with a tool like Beyond Compare.
[IDEA_IOM.zip](https://github.com/idea-statica/ideastatica-public/files/6855738/IDEA_IOM.zip)

As I can see the xmlR files are the same in Case1 and Case2, and the file contains the correct values of Vy, Vz, My, Mz but IDEA StatiCA mixes them for some reason, and the different local coordinate systems has no effect on this behaviour.
I haven’t find any other parameters to set the local system for the internal forces. Did I misunderstand something?
 
Could you please help me to clarify how to solve this problem properly?

**Comment by vojtech-chalupa** [comment]
Hello, thank you for your question and explanation of your problem. I'll try to describe what happens with the vector of internal forces defined in .xmlr file.

1) The signs of forces are changed based on whether the beam is connected by its begin node (relative position = 0) or its end node (relative position = 1). This is expected behavior and this is the adjustment:
float[] begConnVector = { +1f, -1f, -1f, +1f, -1f, +1f };
float[] endConnVector = { -1f, +1f, +1f, -1f, +1f, -1f };
You can also see the issue [#82](https://github.com/idea-statica/iom-examples/issues/82) for further explanation.

2) There is a property that needs to be defined in your .xmlr file - [ResultLocalSystemType](https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.Result.ResultLocalSystemType.html)
By default, it is expected that the results are given in principal axes. In your case (when the cross-section is wider than higher), principal and local systems do not match. It should be specified that the results are in local axes - as a property in ResultOnMember `<LocalSystemType>Local</LocalSystemType>`

I've modified and attached your Case1 project, I am now getting all forces in equilibrium.
[Case1.zip](https://github.com/idea-statica/ideastatica-public/files/6868236/Case1.zip)

**Comment by zsolt4un** [comment]
Dear Vojtěch, Thank you for your answer.
We are using the IdeaRS.OpenModel.dll version 20.0.92.57482. In this version of your API I cannot find the parameter “LocalSystemType”. The constructor of the ResultOnMember object has no such parameter: gcnew ResultOnMember(member,ResultType::InternalForces), and the object also does not have this parameter when it is created.
I guess this is a new parameter in your API version 21.
Does it mean, that in IDEA 20 the internal forces are allways given in the principal axis system of the cross-section? From another point of view, if we start using the 21st version of the IOM and we set the “LocalSystemType” parameter to "Local" then the XmlR file can be opened in IDEA 21 correctly, but in IDEA 20 the internal forces will be wrong, because it does not understand this parameter. So we need special handling for IDEA 20 and 21 separately, or it is better not to use this parameter, but to transform the internal forces to the principal system of the cross-sections for both versions of IDEA?

**Comment by vojtech-chalupa** [comment]
Right, this is exactly the state right now. IDEA StatiCa 20 always expects the results in principal axes of the cross-section, and there is no way to define it differently. Honestly, the implementation is up to you, as we don't have a preference.
You can transform all results to principal axes of the cross-sections, and it will work for all IDEA StatiCa versions.
Or you can start using the property "LocalSystemType"; but this solution will only work for IDEA StatiCa 21 and higher.
