### ISSUE TITLE
[QUESTION] how to save updated parameters in a IdeaCon project

### ISSUE THREAD

**Issue by stevenverwer** [idea-statica/ideastatica-public#82]
How do I save a project with updated parameters?

I tried ideaConnectionClient.ApplyParameters() and ideaConnectionClient.SaveAsProject(), but the parameter values are never updated.

**Comment by vojtech-chalupa** [comment]
The ConnectionCliend.SaveAsProject() should work for you. I presume the project is saved, but the updated parameter values are not? I've planned the fix for the upcoming patch 21.1.2.

**Comment by stevenverwer** [comment]
That is correct. Updating parameters also does not visually change the parameters of a project. So, I cannot see if it changed. Only by calling the calculation() method I can see a difference in the result.

**Comment by nathanlukeIDEA** [comment]
Hi Steven, sorry for taking some time on this. 

The latest release of IdeaStatiCa.PlugIn Nuget Package now includes a `.Save()` method which will save the open file (and applied parameters).

The problem was originally occurring I believe because you cannot SaveAs the file as the same file path as the currently open file. Using a different file path should have allowed you to save as the item with the parameters applied.

Please let me know if the Save() fixes this issue. 

Cheers
Nathan
