### ISSUE TITLE
[FEATURE] get Production Cost from Idea StatiCa Connection

### ISSUE THREAD

**Issue by stevenverwer** [idea-statica/ideastatica-public#84]
Would be great for comparison between similar connections.

This was a question, but I changed it to a feature request to keep track off this issue.

**Comment by vojtech-chalupa** [comment]
The feature is planned for the patch 21.1.2 ~ reading the resulting cost of the connection through API.

**Comment by stevenverwer** [comment]
This is some really good news.

**Comment by vojtech-chalupa** [comment]
The latest release 21.1.4 is now out, you can now read the cost of a connection through an API call, see the updated ConnectionHiddenCalculator. In order to manipulate the costs used for the calculation, you can change them in the Connection app settings, and save them as a default Template. This will ensure that these costs will be used when generating a connection through IOM/API.
